# Docker
docker build -t andro_crawler . 

docker run -v /<some path>:/andro_text andro_crawler

## mongodb docker container 
docker run -d -p 27017:27017 -v /<some path>:/data/db mongo

-d = run as daemon
-p host-port:internal-port
-v host-vol:internal-vol

# Mongodb
mongod --dbpath ./db/       # start server/daemon
mongo                       # opens shell at localhost:27017

show dbs
use <db name>

show collections
db.<collection name>.find().pretty()

# Server

## login

ssh studbernstetter@vingilot

## Copy around
https://askubuntu.com/questions/157381/in-ssh-how-do-i-mv-to-my-local-system

from remote to local:
scp studbernstetter@vingilot:/home/stud/bernstetter/<path> /home/armin/<path>

from local to remote:
scp /home/armin/<path> studbernstetter@vingilot:/home/stud/bernstetter/<path>

## Gitlab container registry

https://gitlab2.informatik.uni-wuerzburg.de/s319059/mprak_crawlers/container_registry

## kubernetes deploy stuff

- see template.yml file

- gitlab deploy tokens: read registry

- in vingilot:
token -> secret erzeugen
kubectl -n studbernstetter create secret docker-registry gitlab-registry --docker-server=gitlab2.informatik.uni-wuerzburg.de:4567 --docker-username=gitlab+deploy-token-12 --docker-password=<pwhere>

secret name (gitlab-registry) in yaml file bei imagePullSecret

kubectl apply -f ta-crawler/ta-crawler.yml

kubectl delete -f ta-crawler/ta-crawler.yml
kubectl -n studbernstetter get pods
kubectl -n studbernstetter describe pods

zugriff auf mongo bash
kubectl -n studbernstetter exec -it ta-crawler-7b8f86687c-474xb -c ta-mongodb bash


## ssh
Host login6
   HostName login6.informatik.uni-wuerzburg.de
   ForwardAgent yes
   user studbernstetter

Host vingilot
   HostName vingilot.informatik.uni-wuerzburg.de
   User studbernstetter
   ProxyCommand ssh login6 nc %h %p



### Error at: https://www.team-andro.com/phpBB3/bankdruecken-enger-weiter-griff-t134131-45.html
('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Traceback (most recent call last):
  File "./ta_crawl.py", line 195, in <module>
    crawl_ta()
  File "./ta_crawl.py", line 64, in crawl_ta
    raise AttributeError("Error at sitemap: " + sitemap)
AttributeError: Error at sitemap: ta-sitemaps/sitemap-google45.xml


admin: freischalten 132.187.14.*
